apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: three-tier
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2  # Use the desired Redis version
        ports:
        - containerPort: 6379
---


# redis-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis2
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379


